//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classifier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Human
    {
        public int ID { get; set; }
        public byte[] HOG { get; set; }
        public int IsHuman { get; set; }
    }
}
